# -*- coding: utf-8 -*-
"""Ecommerce_Product_Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OikbyUG_njK-dIRIDXX5ou7rqnGZmhnv
"""

# Install required libraries
!pip install pandas scikit-learn -q

# Import required libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load the dataset (upload ecommerce_orders.csv to the Colab session first)
data = pd.read_csv("/content/Dataset for Data Analytics - Sheet1.csv")

# Display the dataset
data

# Replace missing coupon codes with a placeholder label
data["CouponCode"] = data["CouponCode"].fillna("NoCoupon")

# Combine relevant order attributes into a single text feature per order
data["Profile"] = data["PaymentMethod"] + " " + data["OrderStatus"] + " " + data["ReferralSource"] + " " + data["CouponCode"]

# Create a text corpus by grouping all order attributes into one profile per product
product_profiles = data.groupby("Product")["Profile"].apply(lambda x: " ".join(x)).reset_index()
product_profiles.columns = ["Product", "ProfileText"]

# Display the product profiles
product_profiles

# Take at least three shopping preferences as user input
user_preferences = ["Debit Card", "Instagram", "SAVE10"]

# Convert the product profile text into TF-IDF vectors
corpus = product_profiles["ProfileText"].tolist()
vectorizer = TfidfVectorizer()
product_vectors = vectorizer.fit_transform(corpus)

# Convert the user preferences into a TF-IDF vector using the same vectorizer
user_text = " ".join(user_preferences)
user_vector = vectorizer.transform([user_text])

# Calculate Cosine Similarity between the user vector and every product profile
similarity_scores = cosine_similarity(user_vector, product_vectors)

# Store similarity scores alongside each product
product_profiles["Similarity Score"] = similarity_scores[0]

# Sort similarity scores in descending order
ranked_products = product_profiles.sort_values(by="Similarity Score", ascending=False)

# Filter and return only the Top 3 recommendations
top_3_recommendations = ranked_products.head(3)

# Display the user's selected shopping preferences
print("User Preferences:")
for preference in user_preferences:
    print("-", preference)

# Display Top 3 recommended products with product name and similarity score
print("Top 3 Recommended Products:\n")
for index, row in top_3_recommendations.iterrows():
    print("Product:", row["Product"])
    print("Similarity Score:", round(row["Similarity Score"], 2))
    print()